# Generated by Django 3.2.5 on 2023-10-04 07:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20231004_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 7, 27, 8, 522835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 7, 27, 8, 522835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 7, 27, 8, 522835, tzinfo=utc)),
        ),
    ]
